# Generated by Django 6.0 on 2026-02-12 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_task_assigned', models.BooleanField(default=True)),
                ('notify_task_updated', models.BooleanField(default=True)),
                ('notify_task_completed', models.BooleanField(default=False)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_milestones', models.BooleanField(default=True)),
                ('notify_deadlines', models.BooleanField(default=True)),
                ('notify_project_updates', models.BooleanField(default=True)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_updated', models.BooleanField(default=False)),
                ('email_mentions', models.BooleanField(default=True)),
                ('email_milestones', models.BooleanField(default=True)),
                ('email_deadlines', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='never', max_length=20)),
                ('digest_time', models.TimeField(default='09:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('mention', 'Mentioned in Comment'), ('milestone_due', 'Milestone Due Soon'), ('milestone_completed', 'Milestone Completed'), ('milestone_overdue', 'Milestone Overdue'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_completed', 'Project Completed'), ('deadline_approaching', 'Deadline Approaching'), ('member_added', 'Added to Team'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx')],
            },
        ),
    ]
