# Generated by Django 5.2.7 on 2025-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='impact',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impact on project progress when completed (0-100%)', max_digits=5),
        ),
    ]
