# Generated by Django 5.2.7 on 2025-11-12 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_multiple',
            field=models.ManyToManyField(blank=True, help_text='Multiple team members assigned to this task', related_name='multi_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
